### ISSUE TITLE
cudf & cugraph error

### ISSUE THREAD

**Issue by ivanfarid** [rapidsai-community/rapidsai-csp-utils#70]
Hi Everyone!! I am trying to install Rapids (cudf & cugraph) via pip using google colab and here are the commands:

!pip install cudf-cu11 dask-cudf-cu11 --extra-index-url=https://pypi.nvidia.com/
!pip install cugraph-cu11 --extra-index-url=https://pypi.nvidia.com/

 several days ago it has no problem, but today it is giving me error as follow:
 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/, https://pypi.nvidia.com/
Collecting cugraph-cu11
  Using cached cugraph_cu11-23.2.0.tar.gz (6.6 kB)
  error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Does anyone can help me with this? Thank you.

**Comment by taureandyernv** [comment]
Thanks for letting us know @ivanfarid !  This was due to Colab moving to Python 3.9, which RAPIDS currently doesn't support any more. It's been temporarily fixed by rolling back to v22.12 with a much more sticky fix in the works.  

Please run the Colab-pip install template as usual; there is no other action that you need to take, as all updates happen in the template's script. :)
